### ISSUE TITLE
Upload video

### ISSUE THREAD

**Issue by datnt** [Fullscreen/yt#17]
Hi claudiofullscreen,

How to upload video by using this library?

**Comment by fusion2004** [comment]
That seems to be the only major feature missing that would stop migration from `youtube_it`. Are there plans in the pipeline to implement it?

**Comment by claudiofullscreen** [comment]
@datnt @fusion2004 Thanks for your feedback. 

I'm implementing features as I need them in my projects, and video upload had not come to my mind yet.
I'll be working on that next and inform you when it's ready.

**Comment by fusion2004** [comment]
Awesome! Thanks for the hard work so far, looks like a solid gem.

**Comment by claudiofullscreen** [comment]
Closed by https://github.com/Fullscreen/yt/pull/19 – @datnt @fusion2004 

I didn't implement the entire resumable session protocol, but just the case when the video upload goes through smoothly. Please give it a try and tell me what you think!
