### ISSUE TITLE
Yt.configure threadsafety

### ISSUE THREAD

**Issue by sbounmy** [Fullscreen/yt#21]
First of all, thank you for this great gem supporting youtube api v3.

AFAIK, `Yt.configure` is not threadsafe because it is an instance "module" variable.
This is not urgent, I would appreciate your feedback on this, I will probably do a pull request later once we decide to replace youtube_it by yt in our app

Cheers,
Stephane.

**Comment by claudiofullscreen** [comment]
@sbounmy Thanks for your feedback!

I never used Yt in that context, so I didn't notice that, but I would love to fix it.

Could you show me an example of how you'd like to use Yt (and you can't right now because of the problem you describe)? 

Thanks again

**Comment by claudiofullscreen** [comment]
Closed due to inactivity. Feel free to re-open if needed.
