### ISSUE TITLE
Channel.videos limited to 500

### ISSUE THREAD

**Issue by catchouli** [Fullscreen/yt#23]
When accessing the videos of a channel with more than 500 videos, Channel.videos seems to be limited to 500 results. For example, for the channel raocow (channel = Yt::Channel.new url: 'http://www.youtube.com/raocow') channel.videos.count == 500 but channel.video_count == 3500 or so.

Googling makes it seem like this might be an API limit? I believe that youtube_it gets all videos for a channel by setting a start index and iterating until all videos are obtained. Is it possible to do such a thing with this library? Otherwise, would it be possible for this to be supported?

I considered writing such a thing myself but I was unsure where it fit in with the architecture of the library.

Thanks for the great software,
Cat

**Comment by claudiofullscreen** [comment]
@Catchouli You are right, I didn't know that 

> The API won't provide more than ~500 search results for any arbitrary query. It's by design. [Link](http://stackoverflow.com/a/23256768)

I'll look into your suggestion and see if I can find a workaround!

**Comment by claudiofullscreen** [comment]
@Catchouli Update your gem (to 0.7.9) and try again, it should work now!

**Comment by catchouli** [comment]
Thanks for the quick response, and sorry I didn't get to try it until now. It works great!
